<?php

return [
    'categories' => [
        ['name' => 'Logistics', 'count' => 2],
        ['name' => 'News', 'count' => 2],
        ['name' => 'Insights', 'count' => 1],
        ['name' => 'Industry', 'count' => 1],
    ],

    'all_tags' => ['Logistics', 'Cargo', 'Maldives', 'Freight', 'News', 'Maritime', 'Customs', 'Supply Chain', 'Import', 'Technology', 'Fleet', 'Resorts'],

    'instagram_images' => [
        'https://images.unsplash.com/photo-1578922746465-3a80a228f223?w=120&h=120&fit=crop&auto=format',
        'https://images.unsplash.com/photo-1494412651409-8963ce7935a7?w=120&h=120&fit=crop&auto=format',
        'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=120&h=120&fit=crop&auto=format',
        'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=120&h=120&fit=crop&auto=format',
        'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=120&h=120&fit=crop&auto=format',
        'https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=120&h=120&fit=crop&auto=format',
    ],

    'posts' => [
        [
            'slug' => 'new-cargo-routes-southern-atolls',
            'tag' => 'LOGISTICS',
            'date' => 'Mar 15, 2025',
            'title' => 'New Cargo Routes Open Across Southern Atolls',
            'excerpt' => 'Litus Maldives has launched two new scheduled cargo routes serving Addu Atoll and Fuvahmulah, reducing delivery times by up to 40%.',
            'hero' => 'https://images.unsplash.com/photo-1578922746465-3a80a228f223?w=1200&h=700&fit=crop&auto=format',
            'thumb' => 'https://images.unsplash.com/photo-1578922746465-3a80a228f223?w=400&h=280&fit=crop&auto=format',
            'author' => [
                'name' => 'Ahmed Rasheed',
                'role' => 'Operations Director',
                'avatar' => 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=80&h=80&fit=crop&auto=format',
                'bio' => "Ahmed leads Litus Maldives' inter-atoll operations, overseeing fleet scheduling, route planning, and delivery reliability across all 26 atolls.",
            ],
            'body' => [
                'Litus Maldives is proud to announce the launch of two new scheduled cargo routes serving the southernmost atolls of the Maldives — Addu Atoll and Fuvahmulah. These long-awaited routes have been introduced in direct response to growing demand from resort operators, local businesses, and island communities in the south.',
                'The new routes operate on a bi-weekly schedule, with dedicated vessels departing from Malé every Tuesday and Friday. Each vessel is equipped to carry refrigerated cargo, general freight, and project materials, ensuring that even the most remote southern islands receive reliable, professional logistics support.',
                'Prior to this expansion, businesses and communities in Addu and Fuvahmulah faced delivery times of up to 10 days due to reliance on informal transport arrangements. With Litus Maldives\' new scheduled service, delivery times have been cut to under 4 days — a reduction of more than 40%.',
            ],
            'quote' => 'Reliable logistics to every atoll is not a luxury — it is the foundation of economic growth across the entire Maldivian archipelago.',
            'body2' => [
                'The expansion also brings the added benefit of professional cargo handling, insurance coverage, and real-time shipment tracking — services that were previously unavailable for freight moving to the far south. Clients can now book cargo, monitor their shipment status, and receive automated delivery notifications through the Litus Maldives client portal.',
                'This launch marks a significant milestone in our commitment to connecting the entire Maldivian archipelago with world-class logistics infrastructure. We remain dedicated to expanding our network further and improving delivery standards for every island we serve.',
            ],
            'tags' => ['Logistics', 'Cargo', 'Maldives', 'Freight', 'Atolls'],
        ],
        [
            'slug' => 'litus-partners-international-freight-network',
            'tag' => 'NEWS',
            'date' => 'Feb 28, 2025',
            'title' => 'Litus Maldives Partners with International Freight Network',
            'excerpt' => 'A landmark agreement expands our door-to-door capabilities for international importers shipping goods into the Maldives.',
            'hero' => 'https://images.unsplash.com/photo-1494412651409-8963ce7935a7?w=1200&h=700&fit=crop&auto=format',
            'thumb' => 'https://images.unsplash.com/photo-1494412651409-8963ce7935a7?w=400&h=280&fit=crop&auto=format',
            'author' => [
                'name' => 'Mohamed Zahid',
                'role' => 'CEO',
                'avatar' => 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop&auto=format',
                'bio' => 'Mohamed Zahid is the founder and CEO of Litus Maldives, with over 15 years of experience building world-class logistics infrastructure across the archipelago.',
            ],
            'body' => [
                'Litus Maldives has signed a landmark partnership agreement with a leading international freight network, significantly expanding our door-to-door freight capabilities for importers shipping goods into the Maldives from global origins.',
                'The agreement grants Litus Maldives preferred partner status within a network of over 120 freight agents across 45 countries, providing our clients with streamlined access to international origin services, competitive ocean and air freight rates, and consolidated shipment options from major global trade hubs including Dubai, Singapore, Colombo, and Shanghai.',
                'This partnership directly addresses one of the most common challenges faced by Maldivian importers — the complexity and cost of coordinating international freight from multiple providers. With this agreement, Litus Maldives can now offer a single point of contact for the entire import journey: from factory floor in any part of the world to island delivery in the Maldives.',
            ],
            'quote' => 'This partnership is a game-changer for our clients. They can now trust Litus Maldives to handle every step — from the manufacturer\'s warehouse anywhere in the world to the final island drop-off.',
            'body2' => [
                'Clients will benefit from dedicated account management, transparent pricing, and a unified tracking platform that provides visibility across both the international and domestic legs of their shipment. Insurance, customs brokerage, and last-mile delivery are all included within a single service agreement.',
                'We expect this partnership to dramatically reduce costs and complexity for our clients, and to attract new international businesses who have previously found Maldivian import logistics prohibitively complicated. Full service availability begins 1 April 2025.',
            ],
            'tags' => ['Partnership', 'International', 'Freight', 'Import', 'News'],
        ],
        [
            'slug' => 'island-supply-chain-resort-demands',
            'tag' => 'INSIGHTS',
            'date' => 'Jan 12, 2025',
            'title' => 'Island Supply Chain: Meeting Resort Demands Year-Round',
            'excerpt' => 'We explore the logistical challenges of supplying luxury resorts through monsoon season.',
            'hero' => 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=1200&h=700&fit=crop&auto=format',
            'thumb' => 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=400&h=280&fit=crop&auto=format',
            'author' => [
                'name' => 'Mariyam Naila',
                'role' => 'Supply Chain Analyst',
                'avatar' => 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=80&h=80&fit=crop&auto=format',
                'bio' => 'Mariyam specialises in supply chain resilience and seasonal logistics planning for island resort operations across the Maldives.',
            ],
            'body' => [
                'Supplying a luxury resort in the Maldives is one of the most logistically complex operations in the hospitality industry. Unlike mainland hotels, Maldivian resorts are entirely dependent on external supply chains — every ingredient, amenity, and spare part must arrive by sea or air, often to islands many hours from the capital.',
                'During the southwest monsoon season (May–October), the challenge intensifies dramatically. Rough seas can prevent vessel movement for days at a time, ferry routes are disrupted, and the risk of cargo damage rises substantially. For a 5-star resort running at full occupancy, even a 24-hour supply disruption can have significant operational and reputational consequences.',
                'Litus Maldives has developed a suite of strategies to ensure continuity of supply throughout the monsoon season, combining advanced weather monitoring, buffer stock planning, and flexible multi-modal logistics to keep resorts fully stocked regardless of conditions.',
            ],
            'quote' => 'The resorts that thrive through monsoon season are those who treat supply chain planning as seriously as they treat guest experience design.',
            'body2' => [
                'Key among these strategies is the use of strategic buffer inventory — working with resort procurement teams to identify critical items and build 2–3 week safety stock reserves before the peak monsoon months. Combined with priority air freight arrangements for perishables and fast-moving items, this approach has allowed our resort clients to maintain uninterrupted operations through even the most severe weather events.',
                'Looking ahead, Litus Maldives is investing in expanded cold-chain capacity and a real-time weather-responsive scheduling system that will automatically reroute and reprioritise shipments based on live sea state data. We believe logistics intelligence is the next frontier in island supply chain resilience.',
            ],
            'tags' => ['Supply Chain', 'Resorts', 'Monsoon', 'Insights', 'Logistics'],
        ],
        [
            'slug' => 'future-maritime-logistics-maldives',
            'tag' => 'INDUSTRY',
            'date' => 'Dec 5, 2024',
            'title' => 'The Future of Maritime Logistics in the Maldives',
            'excerpt' => 'Fleet modernisation, digital tracking and rising sea freight costs — the trends reshaping archipelago logistics.',
            'hero' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200&h=700&fit=crop&auto=format',
            'thumb' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=400&h=280&fit=crop&auto=format',
            'author' => [
                'name' => 'Ahmed Rasheed',
                'role' => 'Operations Director',
                'avatar' => 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=80&h=80&fit=crop&auto=format',
                'bio' => "Ahmed leads Litus Maldives' inter-atoll operations, overseeing fleet scheduling, route planning, and delivery reliability across all 26 atolls.",
            ],
            'body' => [
                'The maritime logistics sector in the Maldives stands at an inflection point. After decades of relatively informal freight arrangements, a combination of economic growth, rising resort standards, and digital transformation is driving rapid modernisation across the entire supply chain.',
                'Three forces are reshaping the industry at pace: fleet modernisation, the adoption of digital tracking and booking platforms, and structurally higher global sea freight costs that are compelling Maldivian businesses to rethink their import strategies.',
                'Fleet modernisation is the most visible change. Older, single-purpose wooden cargo dhonis are being replaced by purpose-built steel vessels equipped with refrigerated holds, crane systems, and GPS tracking. These vessels can carry significantly larger loads, operate safely in a wider range of sea conditions, and meet the cargo security standards demanded by international insurers.',
            ],
            'quote' => 'Digital transformation in logistics is not about replacing human expertise — it is about giving that expertise better tools to deliver exceptional outcomes.',
            'body2' => [
                'Alongside hardware upgrades, digital platforms are transforming how cargo is booked, tracked, and managed. Clients increasingly expect the same visibility for their island freight as they receive from global courier services — real-time location, exception alerts, and digital proof of delivery.',
                'Litus Maldives is at the forefront of this transformation, having invested significantly in our client-facing tracking platform, warehouse management systems, and mobile delivery confirmation tools. We believe the companies that invest in logistics technology today will be the dominant players in Maldivian freight for the next decade.',
            ],
            'tags' => ['Maritime', 'Technology', 'Trends', 'Industry', 'Fleet'],
        ],
        [
            'slug' => 'customs-brokerage-guide',
            'tag' => 'LOGISTICS',
            'date' => 'Nov 20, 2024',
            'title' => 'Customs Brokerage: What Every Maldivian Importer Should Know',
            'excerpt' => 'A practical guide to Maldives Customs Service procedures, duty rates, and professional brokerage.',
            'hero' => 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=1200&h=700&fit=crop&auto=format',
            'thumb' => 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=400&h=280&fit=crop&auto=format',
            'author' => [
                'name' => 'Mariyam Naila',
                'role' => 'Supply Chain Analyst',
                'avatar' => 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=80&h=80&fit=crop&auto=format',
                'bio' => 'Mariyam specialises in supply chain resilience and seasonal logistics planning for island resort operations across the Maldives.',
            ],
            'body' => [
                'Customs clearance is one of the most misunderstood elements of the import process for Maldivian businesses. Errors in documentation, incorrect tariff classification, or missed compliance requirements can result in costly delays, storage charges, and in some cases, confiscation of goods.',
                'The Maldives Customs Service (MCS) operates under the Maldives Customs Act and applies tariff rates that vary by product category — from zero-rated essential food items to 100%+ duties on certain luxury goods and alcohol (for licensed resort operations). Understanding which tariff applies to your imports, and ensuring your documentation matches exactly, is essential to a smooth clearance process.',
                'A professional customs broker acts as your authorised agent with the MCS, preparing and submitting all required declarations, calculating duty liability, liaising with inspectors, and coordinating the release of your cargo. The value of this service goes far beyond paperwork — an experienced broker knows which inspectors to liaise with, what documentation will be scrutinised, and how to resolve disputes quickly.',
            ],
            'quote' => 'Good documentation is the difference between a cargo that clears in hours and one that sits in bonded storage for days, accruing costs with every sunrise.',
            'body2' => [
                'For businesses importing regularly into the Maldives, establishing a relationship with a licensed customs broker is one of the highest-return investments in your supply chain. The cost of professional brokerage is almost always lower than the cost of a single clearance delay.',
                'Litus Maldives maintains a team of fully licensed customs brokers with deep experience across all major import categories — from food and beverage to construction materials, marine equipment, and resort FF&E. Our brokers are available 7 days a week to manage your clearances and keep your supply chain moving.',
            ],
            'tags' => ['Customs', 'Import', 'Compliance', 'Brokerage', 'Guide'],
        ],
        [
            'slug' => 'litus-fleet-expansion-two-new-vessels',
            'tag' => 'NEWS',
            'date' => 'Oct 9, 2024',
            'title' => 'Litus Maldives Fleet Expansion: Two New Vessels',
            'excerpt' => 'Two new cargo vessels join our inter-atoll fleet, increasing capacity by 35% and serving 18 additional islands.',
            'hero' => 'https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=1200&h=700&fit=crop&auto=format',
            'thumb' => 'https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=400&h=280&fit=crop&auto=format',
            'author' => [
                'name' => 'Mohamed Zahid',
                'role' => 'CEO',
                'avatar' => 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop&auto=format',
                'bio' => 'Mohamed Zahid is the founder and CEO of Litus Maldives, with over 15 years of experience building world-class logistics infrastructure across the archipelago.',
            ],
            'body' => [
                'Litus Maldives is delighted to announce the addition of two purpose-built cargo vessels to our inter-atoll fleet. The new vessels — MV Litus Horizon and MV Litus Pioneer — entered service on 1 October 2024 following a commissioning period, and are now operating on scheduled routes across the northern and central atolls.',
                'Each vessel has a cargo capacity of 180 metric tons, significantly larger than the vessels they replace. Both are equipped with refrigerated holds for cold-chain cargo, an onboard crane for remote island discharge operations, satellite tracking, and modern crew safety systems. The design specification was developed in close consultation with our operations team to address the specific requirements of Maldivian inter-atoll freight.',
                'The fleet expansion increases Litus Maldives\' total carrying capacity by 35% and allows us to extend scheduled services to 18 islands that were previously served only by irregular charter arrangements. For communities and businesses on these islands, this represents a transformational improvement in supply chain reliability.',
            ],
            'quote' => 'MV Litus Horizon and MV Litus Pioneer are not just ships — they are a statement of our long-term commitment to the people and businesses of every atoll in the Maldives.',
            'body2' => [
                'The investment in new vessels is part of a broader three-year fleet modernisation programme that will see Litus Maldives retire all remaining older vessels and replace them with purpose-built, GPS-tracked cargo ships by the end of 2026.',
                'Booking for cargo on the new routes is now open through the Litus Maldives client portal. Existing clients will be automatically migrated to the most appropriate route based on their destination islands. For enquiries, please contact our operations centre.',
            ],
            'tags' => ['Fleet', 'Vessels', 'Expansion', 'News', 'Growth'],
        ],
    ],
];
